matrix:
  include:
    - language: java
    jdk:
      - oraclejdk11

    sudo: enabled

      - language: node_js
    node_js:
      - 10

    addons:
      apt:
        packages:
          - libgconf-2-4

    install:
      - npm ci

    script:
      - $(npm bin)/cypress run

    cache:
      npm: true
      directories:
        - ~/.cache