---
matrix:
  include:
    -
      jdk:
        - oraclejdk11
      language: java
      sudo: enabled
    -
      addons:
        apt:
          packages:
            - libgconf-2-4
      before_script:
        - "npm start -- --silent &"
      cache:
        directories:
          - ~/.npm
          - ~/.cache
      install:
        - "npm ci"
      language: node_js
      node_js:
        - 10
      script:
        - "npm run cypress:run"
