language: java
jdk:
  - oraclejdk11
  # cache for jdk?
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    "aa7a312d-3afd-4446-8392-8f3934e012b2"
  app: skateplanner
  on:
    repo: Skateplanner-Co-KG/skateplanner